#! /bin/bash
#
# Scritto da Filippo Bonazzi <f.bonazzi@davide.it> 2012
#
# Lo script richiede il programma youtube-dl disponibile nei repository di Ubuntu

video="$HOME/Video"

function usage {
  echo "Numero di parametri errato!"
  echo -e "Uso: $0 [URL]\n"
  echo "Questo script scarica il video di YouTube fornito come parametro."
  echo "Il video viene salvato nella cartella $video."
}

if [ $# -ne 1 ]
then
  usage
  exit 1
fi

cd "$video"
youtube-dl -o "%(title)s.%(ext)s" $1
